import type { LotCategoryLetter } from './lotCategory'

export const buildingData: Record<string, string> = {
  'B2': 'Quarry Dock',
  'B3': 'Paper Mill',
  'B4': 'Power Plant',
  'B6': 'Housing',
  'B7': 'Marv’s Marina',
  'B8': 'Housing',
  'B10': 'Luxury Boat Tours',
  'B11': 'Fish Market',
  'B12': 'Riverfront Hotel',
  'B14': 'Housing',
  'B15': 'Marina',
  'B16': 'Housing',
  'B18': 'River arts Mus.',
  'B19': 'Harbor Warehouse',
  'B20': 'Founders mill',
  'C2': 'Granite Quarry',
  'C3': 'Anchor Tenet',
  'C4': 'Landmark Exchange',
  'C6': 'Cannery',
  'C7': 'Anchor Tenet',
  'C8': 'Natalia’s Nursery',
  'C10': 'Housing',
  'C11': 'Union',
  'C12': 'Housing',
  'C14': 'Brack Biking',
  'C15': 'Anchor Tenet',
  'C16': 'The Promenade',
  'C18': 'Hotel',
  'C19': 'Anchor Tenet',
  'C20': 'Warehouse',
  'D2': 'High Mountain',
  'D3': 'Housing',
  'D4': 'Dining',
  'D6': 'Med Clinic',
  'D7': 'WholesaleDistribution',
  'D8': 'Grocery',
  'D10': 'Apex Quarter',
  'D11': 'Reese Park',
  'D12': 'Dining',
  'D14': 'Hotel',
  'D15': 'Dining',
  'D16': 'Water Works',
  'D18': "Deron's Diner",
  'D19': 'Tre Trucking',
  'D20': 'Gary’s Gas',
  'F2': 'Materials Yard',
  'F3': 'Tre Trucking',
  'F4': 'Grocery',
  'F6': 'Hope Hospital',
  'F7': 'Frankel Park',
  'F8': 'Housing',
  'F10': 'Housing',
  'F11': 'Gilly’s Grocer',
  'F12': 'Housing',
  'F14': 'B Bank',
  'F15': 'JJ Park',
  'F16': 'Hotel',
  'F18': 'Housing',
  'F19': 'WholesaleDistribution',
  'F20': 'Bolt Ranch',
  'G2': 'Gravel Pit',
  'G3': 'Anchor Tenet',
  'G4': 'Housing',
  'G6': 'Hotel',
  'G7': 'Anchor Tenet',
  'G8': 'Housing',
  'G10': 'Housing',
  'G11': 'Anchor Tenet',
  'G12': 'Housing',
  'G14': 'Housing',
  'G15': 'Anchor Tenet',
  'G16': 'The Store',
  'G18': 'Fairgrounds',
  'G19': 'Anchor Tenet',
  'G20': 'Bigger Barns',
  'H2': 'Benny’s BBQ',
  'H3': 'Hotel',
  'H4': 'Tourism',
  'H6': 'Housing',
  'H7': 'Bridgeport',
  'H8': 'Tea Pot',
  'H10': 'The Practice',
  'H11': 'Cornhole Park',
  'H12': 'Courthouse',
  'H14': 'D & D Diner',
  'H15': 'The Union Quarter',
  'H16': 'Housing',
  'H18': 'Jelly Roll Dining',
  'H19': 'Dairy Coop',
  'H20': 'Sasquatch Slaughter',
  'J2': 'Summit Hotel',
  'J3': 'Ski & See',
  'J4': 'Summit Trade',
  'J6': 'Housing',
  'J7': 'Housing',
  'J8': 'Fashion Square',
  'J14': 'Memorial Hotel',
  'J15': 'Housing',
  'J16': 'Housing',
  'J18': 'Hotel',
  'J19': 'Distribution',
  'J20': 'Dairy',
  'K2': 'Myrle’s Market',
  'K3': 'Union',
  'K4': 'Park',
  'K6': 'Grocery',
  'K7': 'Anchor Tenet',
  'K8': 'City Hall',
  'K11': 'Church',
  'K14': 'Firehouse 01',
  'K15': 'Anchor Tenet',
  'K16': 'Grocery',
  'K18': 'Kiki Park',
  'K19': 'Union',
  'K20': 'Farmer’s Market',
  'L2': 'Highland Lodge',
  'L3': 'Biking Tours',
  'L4': 'Housing',
  'L6': 'Housing',
  'L7': 'Housing',
  'L8': 'Hotel',
  'L14': 'History Mus.',
  'L15': 'Housing',
  'L16': 'Housing',
  'L18': 'Cowboy Hotel',
  'L19': 'Distribution',
  'L20': 'Pops Poultry',
  'N2': 'Brax Trail Tours',
  'N3': 'Hotel',
  'N4': 'Grocery',
  'N6': 'Housing',
  'N7': 'The Icon',
  'N8': 'Taylor Made Cakes',
  'N10': 'Police',
  'N11': "Outlaw's Park",
  'N12': 'The Grand',
  'N14': 'Tourism',
  'N15': 'The Practice',
  'N16': 'Housing',
  'N18': 'Cal’s Oil',
  'N19': 'Frontier Market',
  'N20': 'Em’s Equine',
  'O2': 'Silver mine',
  'O3': 'Anchor Tenet',
  'O4': 'Housing',
  'O6': 'Hotel',
  'O7': 'Anchor Tenet',
  'O8': "Camilla's Travel",
  'O10': 'Housing',
  'O11': 'Anchor Tenet',
  'O12': 'Housing',
  'O14': 'Dining',
  'O15': 'Anchor Tenet',
  'O16': 'Housing',
  'O18': 'Trade Market',
  'O19': 'Anchor Tenet',
  'O20': 'Grain Silo',
  'P2': 'Cal’s Oil',
  'P3': 'Materials Yard',
  'P4': 'Distribution',
  'P6': 'Public Works',
  'P7': 'Rybo Park',
  'P8': 'Housing',
  'P10': 'B Bank',
  'P11': 'Grocery',
  'P12': 'Housing',
  'P14': 'Housing',
  'P15': 'Birdo Park',
  'P16': 'Grocery',
  'P18': 'Hotel',
  'P19': 'WholesaleDistribution',
  'P20': 'Bigger Barns',
  'R2': 'Copper Mine',
  'R3': 'Housing',
  'R4': 'Sweet Sauce',
  'R6': 'Hotel',
  'R7': 'Housing',
  'R8': 'Grocery',
  'R10': 'Hotel',
  'R11': 'Railhouse',
  'R12': 'Dave’s Dining',
  'R14': 'Taylor’s Grocer',
  'R15': 'Housing',
  'R16': 'Children’s Hosp',
  'R18': 'Housing',
  'R19': 'Grocery',
  'R20': 'Grebaes Grainery',
  'S2': 'Equip Service',
  'S3': 'Anchor Tenet',
  'S4': 'Grocery',
  'S6': 'Titan Metal Dist.',
  'S7': 'Anchor Tenet',
  'S8': 'Frame Works',
  'S10': 'Warehouse',
  'S11': 'Union',
  'S12': 'Shamwow Storage',
  'S14': 'Hotel',
  'S15': 'Anchor Tenet',
  'S16': 'Family Med',
  'S18': "Reggie's",
  'S19': 'Anchor Tenet',
  'S20': 'Sal’s Storage',
  'T2': 'Timber yard',
  'T3': 'WholesaleDistribution',
  'T4': 'Train terminal',
  'T6': 'Materials Yard',
  'T7': 'Cornelius’ Concrete',
  'T8': 'Tre Trucking',
  'T10': 'Steel Smelter',
  'T11': 'I Track\n(D)',
  'T12': 'Ike’s Iron Foundry',
  'T14': 'Gary’s Gas',
  'T15': 'Auto Mall',
  'T16': 'Tre Trucking',
  'T18': 'Train terminal',
  'T19': 'Wheezy Warehouse',
  'T20': 'Founders Mill',
}

export const lotCategoryData: Record<string, LotCategoryLetter> = {
  'B2': 'D',
  'B3': 'I',
  'B4': 'O',
  'B6': 'H',
  'B7': 'D',
  'B8': 'H',
  'B10': 'E',
  'B11': 'M',
  'B12': 'T',
  'B14': 'H',
  'B15': 'D',
  'B16': 'H',
  'B18': 'E',
  'B19': 'S',
  'B20': 'I',
  'C2': 'I',
  'C3': 'AT',
  'C4': 'M',
  'C6': 'I',
  'C7': 'AT',
  'C8': 'M',
  'C10': 'H',
  'C12': 'H',
  'C14': 'E',
  'C15': 'AT',
  'C16': 'M',
  'C18': 'T',
  'C19': 'AT',
  'C20': 'S',
  'D2': 'T',
  'D3': 'H',
  'D4': 'F',
  'D6': 'M',
  'D7': 'D',
  'D8': 'F',
  'D10': 'M',
  'D11': 'P',
  'D12': 'F',
  'D14': 'T',
  'D15': 'F',
  'D16': 'C',
  'D18': 'F',
  'D19': 'D',
  'D20': 'O',
  'F2': 'S',
  'F3': 'D',
  'F4': 'F',
  'F6': 'C',
  'F7': 'P',
  'F8': 'H',
  'F10': 'H',
  'F11': 'F',
  'F12': 'H',
  'F14': 'M',
  'F15': 'P',
  'F16': 'T',
  'F18': 'H',
  'F19': 'D',
  'F20': 'M',
  'G2': 'I',
  'G3': 'AT',
  'G4': 'H',
  'G6': 'T',
  'G7': 'AT',
  'G8': 'H',
  'G10': 'H',
  'G11': 'AT',
  'G12': 'H',
  'G14': 'H',
  'G15': 'AT',
  'G16': 'F',
  'G18': 'E',
  'G19': 'AT',
  'G20': 'S',
  'H2': 'F',
  'H3': 'T',
  'H4': 'E',
  'H6': 'H',
  'H7': 'M',
  'H8': 'F',
  'H10': 'M',
  'H11': 'P',
  'H12': 'C',
  'H14': 'F',
  'H15': 'M',
  'H16': 'H',
  'H18': 'F',
  'H19': 'F',
  'H20': 'M',
  'J2': 'T',
  'J3': 'E',
  'J4': 'M',
  'J6': 'H',
  'J7': 'H',
  'J8': 'M',
  'J14': 'T',
  'J15': 'H',
  'J16': 'H',
  'J18': 'T',
  'J19': 'D',
  'J20': 'F',
  'K2': 'M',
  'K4': 'P',
  'K6': 'F',
  'K7': 'AT',
  'K8': 'C',
  'K14': 'C',
  'K15': 'AT',
  'K16': 'F',
  'K18': 'P',
  'K20': 'M',
  'L2': 'T',
  'L3': 'E',
  'L4': 'H',
  'L6': 'H',
  'L7': 'H',
  'L8': 'T',
  'L14': 'E',
  'L15': 'H',
  'L16': 'H',
  'L18': 'T',
  'L19': 'D',
  'L20': 'F',
  'N2': 'E',
  'N3': 'T',
  'N4': 'F',
  'N6': 'H',
  'N7': 'M',
  'N8': 'F',
  'N10': 'C',
  'N11': 'P',
  'N12': 'T',
  'N14': 'E',
  'N15': 'M',
  'N16': 'H',
  'N18': 'O',
  'N19': 'M',
  'N20': 'I',
  'O2': 'I',
  'O3': 'AT',
  'O4': 'H',
  'O6': 'T',
  'O7': 'AT',
  'O8': 'E',
  'O10': 'H',
  'O11': 'AT',
  'O12': 'H',
  'O14': 'F',
  'O15': 'AT',
  'O16': 'H',
  'O19': 'AT',
  'O20': 'F',
  'P2': 'O',
  'P3': 'S',
  'P4': 'D',
  'P6': 'C',
  'P7': 'P',
  'P8': 'H',
  'P10': 'M',
  'P11': 'F',
  'P12': 'H',
  'P14': 'H',
  'P15': 'P',
  'P16': 'F',
  'P18': 'T',
  'P19': 'D',
  'P20': 'S',
  'R2': 'I',
  'R3': 'H',
  'R4': 'F',
  'R6': 'T',
  'R7': 'H',
  'R8': 'F',
  'R10': 'T',
  'R11': 'M',
  'R12': 'F',
  'R14': 'F',
  'R15': 'H',
  'R16': 'C',
  'R18': 'H',
  'R19': 'F',
  'R20': 'F',
  'S2': 'M',
  'S3': 'AT',
  'S4': 'F',
  'S6': 'D',
  'S7': 'AT',
  'S8': 'M',
  'S10': 'S',
  'S12': 'S',
  'S14': 'T',
  'S15': 'AT',
  'S16': 'M',
  'S18': 'F',
  'S19': 'AT',
  'S20': 'S',
  'T2': 'I',
  'T3': 'D',
  'T4': 'D',
  'T6': 'S',
  'T7': 'I',
  'T8': 'D',
  'T10': 'I',
  'T11': 'D',
  'T12': 'I',
  'T14': 'O',
  'T15': 'M',
  'T16': 'D',
  'T18': 'D',
  'T19': 'S',
  'T20': 'I',
}

export const civicVariantByCell: Record<string, 'city-hall' | 'courthouse' | 'police' | 'civic-center'> = {
  'D16': 'civic-center',
  'F6': 'civic-center',
  'H12': 'courthouse',
  'K8': 'city-hall',
  'K14': 'civic-center',
  'N10': 'police',
  'P6': 'civic-center',
  'R16': 'civic-center',
}
