import type { LotCategoryLetter } from './lotCategory'

/**
 * GENERATED from scripts/board-source.csv by scripts/genBoardLotData.mjs — do not hand-edit.
 * Board-design (spreadsheet) coordinates are offset one column from engine coordinates:
 * spreadsheet A5 = engine B5. Engine row 1/21 and columns A/U are the bleed bands.
 */
export const buildingData: Record<string, string> = {
  'B2': 'Paper Mill',
  'C2': 'Housing',
  'D2': 'Power Plant',
  'F2': 'Home Market',
  'G2': 'Gravel Pit',
  'H2': 'Flying B Ranch',
  'J2': 'Wheezy Market',
  'K2': 'Lite Work',
  'L2': 'Myrle’s Market',
  'N2': 'Summit Hotel',
  'O2': 'Silver mine',
  'P2': 'Mountain Market',
  'R2': 'Power Plant',
  'S2': 'Housing',
  'T2': 'Timber yard',
  'B3': 'Housing',
  'C3': 'Anchor Tenet',
  'D3': 'High Mountain',
  'F3': 'Housing',
  'G3': 'Anchor Tenet',
  'H3': 'Benny’s BBQ',
  'J3': 'Bigger Barns',
  'K3': 'Anchor Tenet',
  'L3': 'Ski & See',
  'N3': 'Grocery',
  'O3': 'Anchor Tenet',
  'P3': 'Housing',
  'R3': 'Highland Lodge',
  'S3': 'Anchor Tenet',
  'T3': 'Housing',
  'B4': 'Quarry Dock',
  'C4': 'Little B Park',
  'D4': 'Hope Hospital',
  'F4': 'The Practice',
  'G4': 'Kiki Park',
  'H4': 'Housing',
  'J4': 'Summit Market',
  'K4': 'Housing',
  'L4': 'Taylor’s Grocer',
  'N4': 'Housing',
  'O4': 'Big K Park',
  'P4': 'DIY Depot',
  'R4': 'Public Works',
  'S4': 'Calico Park',
  'T4': 'I-Track',
  'B6': 'Housing',
  'C6': 'Bam Bam Distributn',
  'D6': 'Med Clinic',
  'F6': 'Gary’s gas',
  'G6': 'Shamwow Storage',
  'H6': 'Housing',
  'J6': 'Housing',
  'K6': 'The Practice',
  'L6': 'Housing',
  'N6': 'Housing',
  'O6': 'Shamwow Storage',
  'P6': 'Cal’s Oil',
  'R6': 'Watts Electric',
  'S6': 'Bam Bam Distributn',
  'T6': 'Housing',
  'B7': 'Riverfront Hotel',
  'C7': 'Anchor Tenet',
  'D7': 'Frankel Park',
  'F7': 'Bam Bam Distributn',
  'G7': 'Anchor Tenet',
  'H7': 'Bridgeport',
  'J7': 'Fashion Square',
  'K7': 'Anchor Tenet',
  'L7': 'Grocery',
  'N7': 'The Icon',
  'O7': 'Anchor Tenet',
  'P7': 'Bam Bam Distributn',
  'R7': 'Rybo Park',
  'S7': 'Anchor Tenet',
  'T7': 'Hotel',
  'B8': 'Housing',
  'C8': 'Landmark Exchange',
  'D8': 'Gilly’s Grocery',
  'F8': 'Housing',
  'G8': 'Tea Pot',
  'H8': 'Camilla’s Travel',
  'J8': 'City Hall',
  'K8': 'Prophet’s Park',
  'L8': 'Red Brick Hotel',
  'N8': 'Art Museum',
  'O8': 'Taylor Made Cakes',
  'P8': 'Housing',
  'R8': 'Grebaes Grainery',
  'S8': 'Frame Works',
  'T8': 'Housing',
  'B10': 'Fish Market',
  'C10': 'Luxury Boat Tours',
  'D10': 'Reggie’s',
  'F10': 'Housing',
  'G10': 'Gilly’s Grocer',
  'H10': 'Hope Hotel',
  'N10': 'Police',
  'O10': 'Railhouse',
  'P10': 'Housing',
  'R10': 'Dairy Coop',
  'S10': 'Bigger Barns',
  'T10': 'Steel Smelter',
  'B11': 'Marina',
  'C11': 'Anchor Tenet',
  'D11': 'Housing',
  'F11': 'The Practice',
  'G11': 'Anchor Tenet',
  'H11': 'Cornhole Park',
  'N11': 'Outlaw’s Park',
  'O11': 'Anchor Tenet',
  'P11': 'The Practice',
  'R11': 'Housing',
  'S11': 'Anchor Tenet',
  'T11': 'J Track',
  'B12': 'Taylor Boats',
  'C12': 'Bigger Barns',
  'D12': 'Cornelius Market',
  'F12': 'Housing',
  'G12': 'The Practice',
  'H12': 'Courthouse',
  'N12': 'The Grand',
  'O12': 'Grocery',
  'P12': 'Housing',
  'R12': 'Dave’s Dining',
  'S12': 'Will Theater',
  'T12': 'Ike’s Iron Foundry',
  'B14': 'Housing',
  'C14': 'The Promenade',
  'D14': 'D & D Diner',
  'F14': 'Housing',
  'G14': 'The Store',
  'H14': 'History Museum',
  'J14': 'Memorial Hotel',
  'K14': 'City Creek Park',
  'L14': 'Firehouse 01',
  'N14': 'Tourism',
  'O14': 'Dining',
  'P14': 'Housing',
  'R14': 'Taylor’s Grocer',
  'S14': 'Auto Mall',
  'T14': 'Housing',
  'B15': 'Leymie Lakhouse',
  'C15': 'Anchor Tenet',
  'D15': 'JJ Park',
  'F15': 'Bam Bam Distributn',
  'G15': 'Anchor Tenet',
  'H15': 'The Union Quarter',
  'J15': 'Grocery',
  'K15': 'Anchor Tenet',
  'L15': 'City Creek',
  'N15': 'B Bank',
  'O15': 'Anchor Tenet',
  'P15': 'Bam Bam Distributn',
  'R15': 'Birdo Park',
  'S15': 'Anchor Tenet',
  'T15': 'Hotel',
  'B16': 'Housing',
  'C16': 'Bam Bam Distributn',
  'D16': 'Prefect Plumbing',
  'F16': 'Cal’s Oil',
  'G16': 'Shamwow Storage',
  'H16': 'Housing',
  'J16': 'Housing',
  'K16': 'Natalia’s Nursery',
  'L16': 'Housing',
  'N16': 'Housing',
  'O16': 'Shamwow Storage',
  'P16': 'Gary’s gas',
  'R16': 'The Practice',
  'S16': 'Bam Bam Distributn',
  'T16': 'Housing',
  'B18': 'Marv’s Marina',
  'C18': 'Big B Park',
  'D18': 'Water Works',
  'F18': 'Watering Hole',
  'G18': 'Reese Park',
  'H18': 'Housing',
  'J18': 'Pops Poultry',
  'K18': 'Housing',
  'L18': 'Grebaes Grainery',
  'N18': 'Housing',
  'O18': 'Mqil Park',
  'P18': 'Family Med',
  'R18': 'Children’s Hosp',
  'S18': 'Janie Park',
  'T18': 'L Track',
  'B19': 'Housing',
  'C19': 'Anchor Tenet',
  'D19': 'Hotel',
  'F19': 'Housing',
  'G19': 'Anchor Tenet',
  'H19': 'Taylor’s Grocer',
  'J19': 'Fairgrounds',
  'K19': 'Anchor Tenet',
  'L19': 'Bigger Barns',
  'N19': 'Jelly Roll Diner',
  'O19': 'Anchor Tenet',
  'P19': 'Housing',
  'R19': 'Cowboy Hotel',
  'S19': 'Anchor Tenet',
  'T19': 'Housing',
  'B20': 'Founders mill',
  'C20': 'Housing',
  'D20': 'Power Plant',
  'F20': 'Frontier Market',
  'G20': 'Copper Mine',
  'H20': 'Bolt Ranch',
  'J20': 'Sausquatch Market',
  'K20': 'Lite Work',
  'L20': 'Heart of the Country',
  'N20': 'Cowboy Hotel',
  'O20': 'Em’s Equine',
  'P20': 'Farmer’s Market',
  'R20': 'Power Plant',
  'S20': 'Housing',
  'T20': 'Granite Quarry',
}

export const lotCategoryData: Record<string, LotCategoryLetter> = {
  'B2': 'I',
  'C2': 'H',
  'D2': 'O',
  'F2': 'M',
  'G2': 'I',
  'H2': 'T',
  'J2': 'M',
  'K2': 'D',
  'L2': 'M',
  'N2': 'T',
  'O2': 'I',
  'P2': 'M',
  'R2': 'O',
  'S2': 'H',
  'T2': 'I',
  'B3': 'H',
  'C3': 'AT',
  'D3': 'T',
  'F3': 'H',
  'G3': 'AT',
  'H3': 'F',
  'J3': 'S',
  'K3': 'AT',
  'L3': 'E',
  'N3': 'F',
  'O3': 'AT',
  'P3': 'H',
  'R3': 'T',
  'S3': 'AT',
  'T3': 'H',
  'B4': 'D',
  'C4': 'P',
  'D4': 'C',
  'F4': 'M',
  'G4': 'P',
  'H4': 'H',
  'J4': 'F',
  'K4': 'H',
  'L4': 'F',
  'N4': 'H',
  'O4': 'P',
  'P4': 'M',
  'R4': 'C',
  'S4': 'P',
  'T4': 'D',
  'B6': 'H',
  'C6': 'D',
  'D6': 'M',
  'F6': 'O',
  'G6': 'S',
  'H6': 'H',
  'J6': 'H',
  'K6': 'M',
  'L6': 'H',
  'N6': 'H',
  'O6': 'S',
  'P6': 'O',
  'R6': 'M',
  'S6': 'D',
  'T6': 'H',
  'B7': 'T',
  'C7': 'AT',
  'D7': 'P',
  'F7': 'D',
  'G7': 'AT',
  'H7': 'M',
  'J7': 'M',
  'K7': 'AT',
  'L7': 'F',
  'N7': 'M',
  'O7': 'AT',
  'P7': 'D',
  'R7': 'P',
  'S7': 'AT',
  'T7': 'T',
  'B8': 'H',
  'C8': 'M',
  'D8': 'F',
  'F8': 'H',
  'G8': 'F',
  'H8': 'E',
  'J8': 'C',
  'K8': 'P',
  'L8': 'T',
  'N8': 'E',
  'O8': 'F',
  'P8': 'H',
  'R8': 'F',
  'S8': 'M',
  'T8': 'H',
  'B10': 'I',
  'C10': 'E',
  'D10': 'F',
  'F10': 'H',
  'G10': 'F',
  'H10': 'T',
  'N10': 'C',
  'O10': 'M',
  'P10': 'H',
  'R10': 'M',
  'S10': 'S',
  'T10': 'I',
  'B11': 'D',
  'C11': 'AT',
  'D11': 'H',
  'F11': 'M',
  'G11': 'AT',
  'H11': 'P',
  'N11': 'P',
  'O11': 'AT',
  'P11': 'M',
  'R11': 'H',
  'S11': 'AT',
  'T11': 'D',
  'B12': 'I',
  'C12': 'S',
  'D12': 'M',
  'F12': 'H',
  'G12': 'M',
  'H12': 'C',
  'N12': 'T',
  'O12': 'F',
  'P12': 'H',
  'R12': 'F',
  'S12': 'E',
  'T12': 'I',
  'B14': 'H',
  'C14': 'M',
  'D14': 'F',
  'F14': 'H',
  'G14': 'F',
  'H14': 'E',
  'J14': 'T',
  'K14': 'P',
  'L14': 'C',
  'N14': 'E',
  'O14': 'F',
  'P14': 'H',
  'R14': 'F',
  'S14': 'M',
  'T14': 'H',
  'B15': 'T',
  'C15': 'AT',
  'D15': 'P',
  'F15': 'D',
  'G15': 'AT',
  'H15': 'M',
  'J15': 'F',
  'K15': 'AT',
  'L15': 'M',
  'N15': 'M',
  'O15': 'AT',
  'P15': 'D',
  'R15': 'P',
  'S15': 'AT',
  'T15': 'T',
  'B16': 'H',
  'C16': 'D',
  'D16': 'M',
  'F16': 'O',
  'G16': 'S',
  'H16': 'H',
  'J16': 'H',
  'K16': 'M',
  'L16': 'H',
  'N16': 'H',
  'O16': 'S',
  'P16': 'O',
  'R16': 'M',
  'S16': 'D',
  'T16': 'H',
  'B18': 'D',
  'C18': 'P',
  'D18': 'C',
  'F18': 'M',
  'G18': 'P',
  'H18': 'H',
  'J18': 'F',
  'K18': 'H',
  'L18': 'F',
  'N18': 'H',
  'O18': 'P',
  'P18': 'M',
  'R18': 'C',
  'S18': 'P',
  'T18': 'D',
  'B19': 'H',
  'C19': 'AT',
  'D19': 'T',
  'F19': 'H',
  'G19': 'AT',
  'H19': 'F',
  'J19': 'E',
  'K19': 'AT',
  'L19': 'S',
  'N19': 'F',
  'O19': 'AT',
  'P19': 'H',
  'R19': 'T',
  'S19': 'AT',
  'T19': 'H',
  'B20': 'I',
  'C20': 'H',
  'D20': 'O',
  'F20': 'M',
  'G20': 'I',
  'H20': 'T',
  'J20': 'M',
  'K20': 'D',
  'L20': 'M',
  'N20': 'T',
  'O20': 'I',
  'P20': 'M',
  'R20': 'O',
  'S20': 'H',
  'T20': 'I',
}

export const civicVariantByCell: Record<string, 'city-hall' | 'courthouse' | 'police' | 'civic-center'> = {
  'D4': 'civic-center',
  'R4': 'civic-center',
  'J8': 'city-hall',
  'N10': 'police',
  'H12': 'courthouse',
  'L14': 'civic-center',
  'D18': 'civic-center',
  'R18': 'civic-center',
}
