import { PropertyCard, ActionCard } from './cardTypes'
import { INCOME_CARD_ACTIONS_BODY, INCOME_CARD_DICE_ROLL_RULE } from './incomeDice'

/** Anchors the Anchor Wild Card may assume on the board (built `plot.builtProperty` becomes this id). */
export const ANCHOR_WILD_CARD_EMULATE_IDS = [
  'church',
  'farm-coop',
  'port-authority',
  'arts-council',
  'tourism-office',
  'media',
  'mafia',
  'news-outlet',
  'regulation-bureau',
  'union',
] as const

/** Civic flex cards may assume these identities on the board (`plot.builtProperty` becomes this id). */
export const CIVIC_VARIANT_PROPERTY_IDS = [
  'city-hall',
  'courthouse',
  'police',
  'civic-center',
] as const

export const propertyCards: PropertyCard[] = [
  ...Array(4).fill(null).map((_, i) => ({
    id: `storage-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Storage',
    buildCost: 4,
    buildIncome: 4,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Storage', 'Warehouse', 'Quarry Dock'],
    category: 'industrial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(3).fill(null).map((_, i) => ({
    id: `storage-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Storage',
    buildCost: 4,
    buildIncome: 4,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Storage', 'Warehouse', 'Quarry Dock'],
    category: 'industrial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(5).fill(null).map((_, i) => ({
    id: `storage-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Storage',
    buildCost: 4,
    buildIncome: 4,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Storage', 'Warehouse', 'Quarry Dock'],
    category: 'industrial' as const,
    district: 'Railway District' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `storage-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Storage',
    buildCost: 4,
    buildIncome: 4,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Storage', 'Warehouse', 'Quarry Dock'],
    category: 'industrial' as const,
    district: 'Farmland' as const
  })),
  
  ...Array(4).fill(null).map((_, i) => ({
    id: `freight-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Freight',
    buildCost: 4,
    buildIncome: 3,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Freight Terminal', 'Marina', 'Distribution', 'Train Terminal'],
    category: 'industrial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `freight-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Freight',
    buildCost: 4,
    buildIncome: 3,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Freight Terminal', 'Marina', 'Distribution', 'Train Terminal'],
    category: 'industrial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(7).fill(null).map((_, i) => ({
    id: `freight-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Freight',
    buildCost: 4,
    buildIncome: 3,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Freight Terminal', 'Marina', 'Distribution', 'Train Terminal'],
    category: 'industrial' as const,
    district: 'Railway District' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `freight-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Freight',
    buildCost: 4,
    buildIncome: 3,
    influence: 0,
    bankValue: 2,
    endGameValue: 4,
    copies: 1,
    buildLocations: ['Freight Terminal', 'Marina', 'Distribution', 'Train Terminal'],
    category: 'industrial' as const,
    district: 'Farmland' as const
  })),
  
  ...Array(1).fill(null).map((_, i) => ({
    id: `mining-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 4,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Granite Quarry', 'Gravel Pit', 'Silver Mine', 'Copper Mine'],
    category: 'industrial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `mining-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 4,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Granite Quarry', 'Gravel Pit', 'Silver Mine', 'Copper Mine'],
    category: 'industrial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `mining-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 4,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Granite Quarry', 'Gravel Pit', 'Silver Mine', 'Copper Mine'],
    category: 'industrial' as const,
    district: 'Railway District' as const
  })),
  
  ...Array(3).fill(null).map((_, i) => ({
    id: `industry-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 6,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Industry', 'Founders Mill', 'Timber Yard'],
    category: 'industrial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `industry-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 6,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Industry', 'Founders Mill', 'Timber Yard'],
    category: 'industrial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `industry-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 6,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Industry', 'Founders Mill', 'Timber Yard'],
    category: 'industrial' as const,
    district: 'Railway District' as const
  })),
  ...Array(3).fill(null).map((_, i) => ({
    id: `industry-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Industry & Mining',
    buildCost: 8,
    buildIncome: 6,
    influence: 0,
    bankValue: 6,
    endGameValue: 6,
    copies: 1,
    buildLocations: ['Industry', 'Founders Mill', 'Timber Yard'],
    category: 'industrial' as const,
    district: 'Farmland' as const
  })),
  
  {
    id: 'civic-center',
    type: 'property',
    name: 'Civic Center',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 0,
    buildLocations: ['Civic', 'Civic Center'],
    specialAbility: 'Influence only on the city block that is built',
    category: 'civic',
    district: 'City Center',
  },
  ...Array(1).fill(null).map((_, i) => ({
    id: `civic-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Civic',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Civic', 'Civic Center'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic' as const,
    district: 'Riverfront' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `civic-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Civic',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Civic', 'Civic Center'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic' as const,
    district: 'Railway District' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `civic-city-${i + 1}`,
    type: 'property' as const,
    name: 'Civic',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Civic', 'Civic Center'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic' as const,
    district: 'City Center' as const
  })),
  {
    id: 'city-hall',
    type: 'property',
    name: 'City Hall',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['City Hall'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic',
    district: 'City Center'
  },
  {
    id: 'courthouse',
    type: 'property',
    name: 'Courthouse',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Courthouse'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic',
    district: 'City Center'
  },
  {
    id: 'police',
    type: 'property',
    name: 'Police',
    buildCost: 8,
    buildIncome: 2,
    influence: 1,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Police'],
    specialAbility: 'When built, choose City Hall, Courthouse, Police, or Civic Center',
    category: 'civic',
    district: 'City Center'
  },
  
  ...Array(1).fill(null).map((_, i) => ({
    id: `museum-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Museum', 'River arts'],
    specialAbility: 'Adds $1M to surrounding properties within the city block, including the additional $1M end game value',
    category: 'commercial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `museum-city-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Museum', 'History Museum'],
    specialAbility: 'Adds $1M to surrounding properties within the city block, including the additional $1M end game value',
    category: 'commercial' as const,
    district: 'City Center' as const
  })),
  
  ...Array(4).fill(null).map((_, i) => ({
    id: `hotel-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Hotel',
    buildCost: 12,
    buildIncome: 5,
    influence: 0,
    bankValue: 6,
    endGameValue: 12,
    copies: 1,
    buildLocations: ['Hotel', 'Riverfront Hotel'],
    category: 'commercial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(5).fill(null).map((_, i) => ({
    id: `hotel-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Hotel',
    buildCost: 12,
    buildIncome: 5,
    influence: 0,
    bankValue: 6,
    endGameValue: 12,
    copies: 1,
    buildLocations: ['Hotel', 'Summit Hotel', 'Highland Lodge'],
    category: 'commercial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(3).fill(null).map((_, i) => ({
    id: `hotel-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Hotel',
    buildCost: 12,
    buildIncome: 5,
    influence: 0,
    bankValue: 6,
    endGameValue: 12,
    copies: 1,
    buildLocations: ['Hotel'],
    category: 'commercial' as const,
    district: 'Railway District' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `hotel-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Hotel',
    buildCost: 12,
    buildIncome: 5,
    influence: 0,
    bankValue: 6,
    endGameValue: 12,
    copies: 1,
    buildLocations: ['Hotel', 'Cowboy Hotel'],
    category: 'commercial' as const,
    district: 'Farmland' as const
  })),
  ...Array(7).fill(null).map((_, i) => ({
    id: `hotel-city-${i + 1}`,
    type: 'property' as const,
    name: 'Hotel',
    buildCost: 12,
    buildIncome: 5,
    influence: 0,
    bankValue: 6,
    endGameValue: 12,
    copies: 1,
    buildLocations: ['Hotel', 'The Grand Hotel', 'Memorial Hotel'],
    category: 'commercial' as const,
    district: 'City Center' as const
  })),
  
  ...Array(1).fill(null).map((_, i) => ({
    id: `park-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Park',
    buildCost: 5,
    buildIncome: 0,
    influence: 1,
    bankValue: 3,
    endGameValue: 0,
    copies: 1,
    buildLocations: ['Park'],
    specialAbility: 'Adds $1M to surrounding properties for each property owned, including end value of surrounding properties',
    category: 'commercial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `park-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Park',
    buildCost: 5,
    buildIncome: 0,
    influence: 1,
    bankValue: 3,
    endGameValue: 0,
    copies: 1,
    buildLocations: ['Park'],
    specialAbility: 'Adds $1M to surrounding properties for each property owned, including end value of surrounding properties',
    category: 'commercial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `park-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Park',
    buildCost: 5,
    buildIncome: 0,
    influence: 1,
    bankValue: 3,
    endGameValue: 0,
    copies: 1,
    buildLocations: ['Park'],
    specialAbility: 'Adds $1M to surrounding properties for each property owned, including end value of surrounding properties',
    category: 'commercial' as const,
    district: 'Farmland' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `park-city-${i + 1}`,
    type: 'property' as const,
    name: 'Park',
    buildCost: 5,
    buildIncome: 0,
    influence: 1,
    bankValue: 3,
    endGameValue: 0,
    copies: 1,
    buildLocations: ['Park'],
    specialAbility: 'Adds $1M to surrounding properties for each property owned, including end value of surrounding properties',
    category: 'commercial' as const,
    district: 'City Center' as const
  })),
  
  ...Array(5).fill(null).map((_, i) => ({
    id: `mixed-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Commercial',
    buildCost: 8,
    buildIncome: 4,
    influence: 0,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Commercial', 'Market', 'Equipment Service', 'Trade Market', 'Fish Market'],
    category: 'commercial' as const,
    district: 'Riverfront' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `mixed-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Commercial',
    buildCost: 8,
    buildIncome: 4,
    influence: 0,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Commercial', 'Market'],
    category: 'commercial' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `mixed-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Commercial',
    buildCost: 8,
    buildIncome: 4,
    influence: 0,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Commercial', 'Equipment Service'],
    category: 'commercial' as const,
    district: 'Railway District' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `mixed-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Commercial',
    buildCost: 8,
    buildIncome: 4,
    influence: 0,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Commercial', "Farmer's Market"],
    category: 'commercial' as const,
    district: 'Farmland' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `mixed-city-${i + 1}`,
    type: 'property' as const,
    name: 'Commercial',
    buildCost: 8,
    buildIncome: 4,
    influence: 0,
    bankValue: 4,
    endGameValue: 8,
    copies: 1,
    buildLocations: ['Commercial'],
    category: 'commercial' as const,
    district: 'City Center' as const
  })),
  
  ...Array(7).fill(null).map((_, i) => ({
    id: `housing-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Housing',
    buildCost: 10,
    buildIncome: 5,
    influence: 0,
    bankValue: 4,
    endGameValue: 10,
    copies: 1,
    buildLocations: ['Housing'],
    specialAbility: 'Can build >4 stories: Cost 18M, Income 10M, Bank 4M, End Game 18M, Influence -1',
    category: 'residential' as const,
    district: 'Riverfront' as const
  })),
  ...Array(5).fill(null).map((_, i) => ({
    id: `housing-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Housing',
    buildCost: 10,
    buildIncome: 5,
    influence: 0,
    bankValue: 4,
    endGameValue: 10,
    copies: 1,
    buildLocations: ['Housing'],
    specialAbility: 'Can build >4 stories: Cost 18M, Income 10M, Bank 4M, End Game 18M, Influence -1',
    category: 'residential' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `housing-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Housing',
    buildCost: 10,
    buildIncome: 5,
    influence: 0,
    bankValue: 4,
    endGameValue: 10,
    copies: 1,
    buildLocations: ['Housing'],
    specialAbility: 'Can build >4 stories: Cost 18M, Income 10M, Bank 4M, End Game 18M, Influence -1',
    category: 'residential' as const,
    district: 'Railway District' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `housing-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Housing',
    buildCost: 10,
    buildIncome: 5,
    influence: 0,
    bankValue: 4,
    endGameValue: 10,
    copies: 1,
    buildLocations: ['Housing'],
    specialAbility: 'Can build >4 stories: Cost 18M, Income 10M, Bank 4M, End Game 18M, Influence -1',
    category: 'residential' as const,
    district: 'Farmland' as const
  })),
  ...Array(27).fill(null).map((_, i) => ({
    id: `housing-city-${i + 1}`,
    type: 'property' as const,
    name: 'Housing',
    buildCost: 10,
    buildIncome: 5,
    influence: 0,
    bankValue: 4,
    endGameValue: 10,
    copies: 1,
    buildLocations: ['Housing'],
    specialAbility: 'Can build >4 stories: Cost 18M, Income 10M, Bank 4M, End Game 18M, Influence -1',
    category: 'residential' as const,
    district: 'City Center' as const
  })),
  
  ...Array(1).fill(null).map((_, i) => ({
    id: `grocery-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Grocery'],
    category: 'service' as const,
    district: 'Riverfront' as const
  })),
  ...Array(3).fill(null).map((_, i) => ({
    id: `grocery-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Grocery'],
    category: 'service' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `grocery-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Grocery'],
    category: 'service' as const,
    district: 'Railway District' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `grocery-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Grocery'],
    category: 'service' as const,
    district: 'Farmland' as const
  })),
  ...Array(6).fill(null).map((_, i) => ({
    id: `grocery-city-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Grocery'],
    category: 'service' as const,
    district: 'City Center' as const
  })),
  
  ...Array(2).fill(null).map((_, i) => ({
    id: `power-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Power',
    buildCost: 5,
    buildIncome: 6,
    influence: 0,
    bankValue: 3,
    endGameValue: 5,
    copies: 1,
    buildLocations: ['Fuel', 'Power Plant'],
    category: 'service' as const,
    district: 'Riverfront' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `power-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Power',
    buildCost: 5,
    buildIncome: 6,
    influence: 0,
    bankValue: 3,
    endGameValue: 5,
    copies: 1,
    buildLocations: ['Fuel', 'Power Plant'],
    category: 'service' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `power-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Power',
    buildCost: 5,
    buildIncome: 6,
    influence: 0,
    bankValue: 3,
    endGameValue: 5,
    copies: 1,
    buildLocations: ['Fuel'],
    category: 'service' as const,
    district: 'Railway District' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `power-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Power',
    buildCost: 5,
    buildIncome: 6,
    influence: 0,
    bankValue: 3,
    endGameValue: 5,
    copies: 1,
    buildLocations: ['Fuel'],
    category: 'service' as const,
    district: 'Farmland' as const
  })),
  
  ...Array(2).fill(null).map((_, i) => ({
    id: `tourism-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 0,
    bankValue: 2,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Tourism', 'Fairgrounds'],
    category: 'service' as const,
    district: 'Riverfront' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `tourism-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 0,
    bankValue: 2,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Tourism'],
    category: 'service' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(1).fill(null).map((_, i) => ({
    id: `tourism-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 0,
    bankValue: 2,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Fairgrounds'],
    category: 'service' as const,
    district: 'Farmland' as const
  })),
  ...Array(2).fill(null).map((_, i) => ({
    id: `tourism-city-${i + 1}`,
    type: 'property' as const,
    name: 'Arts & Entertainment',
    buildCost: 6,
    buildIncome: 2,
    influence: 0,
    bankValue: 2,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Tourism'],
    category: 'service' as const,
    district: 'City Center' as const
  })),
  
  ...Array(1).fill(null).map((_, i) => ({
    id: `food-riverfront-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Dining'],
    category: 'service' as const,
    district: 'Riverfront' as const
  })),
  ...Array(3).fill(null).map((_, i) => ({
    id: `food-mountain-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Dining'],
    category: 'service' as const,
    district: 'Mountain Cove' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `food-railway-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Dining'],
    category: 'service' as const,
    district: 'Railway District' as const
  })),
  ...Array(8).fill(null).map((_, i) => ({
    id: `food-farm-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Dining', 'Farm Processing', 'Dairy Co-op', 'Grain Silo'],
    category: 'service' as const,
    district: 'Farmland' as const
  })),
  ...Array(4).fill(null).map((_, i) => ({
    id: `food-city-${i + 1}`,
    type: 'property' as const,
    name: 'Food & Grocery',
    buildCost: 4,
    buildIncome: 2,
    influence: 1,
    bankValue: 3,
    endGameValue: 3,
    copies: 1,
    buildLocations: ['Dining'],
    category: 'service' as const,
    district: 'City Center' as const
  })),
  
  {
    id: 'church',
    type: 'anchor',
    name: 'Church Affiliation',
    subtitle: 'Anchor tenet',
    buildCost: 6,
    buildIncome: 0,
    influence: 1,
    bankValue: 5,
    endGameValue: 6,
    copies: 2,
    buildLocations: ['Any center anchor except Union'],
    specialAbility:
      'INFLUENCE: +1 (entire board; max +1 from Church toward any single roll)\n' +
      'INCOME: +1 (block) — each of your other built properties in the same city block as a Church anchor you own gains +1 during Income\n' +
      'Screen notification: Church affiliation created!\n' +
      'End game value: 6M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet (AT) except Union and any already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'farm-coop',
    type: 'anchor',
    name: 'Farm Bureau',
    subtitle: 'Anchor tenet',
    buildCost: 4,
    buildIncome: 2,
    influence: 2,
    bankValue: 3,
    endGameValue: 2,
    copies: 3,
    buildLocations: ['Any anchor adjacent to farmland except Union'],
    specialAbility:
      'INFLUENCE: +1 (Farmland; max +1 from Farm Bureau toward Hostile Takeover on eligible Farmland targets)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'TAKEOVER (Hostile Takeover): +1 attacker influence when the target lot is Farmland — counted only on that property’s city block with other anchor takeover modifiers\n' +
      'Screen notification: Farm Bureau formed!\n' +
      'End game value: 2M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet adjacent to farmland, except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'port-authority',
    type: 'anchor',
    name: 'Port Authority',
    subtitle: 'Anchor tenet',
    buildCost: 2,
    buildIncome: 0,
    influence: 1,
    bankValue: 2,
    endGameValue: 2,
    copies: 3,
    buildLocations: ['Any center AT adjacent to the railway district except Union'],
    specialAbility:
      'INFLUENCE: +1 (Railway district; max +1 toward Hostile Takeover on eligible Railway targets)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'TAKEOVER (Hostile Takeover): +1 attacker influence when the target lot is in the Railway district — counted only on that property’s city block\n' +
      'Screen notification: Port Authority engineered!\n' +
      'End game value: 2M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet adjacent to the railway district, except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'arts-council',
    type: 'anchor',
    name: 'Arts Council',
    subtitle: 'Anchor tenet',
    buildCost: 2,
    buildIncome: 0,
    influence: 1,
    bankValue: 2,
    endGameValue: 2,
    copies: 3,
    buildLocations: ['Any center AT adjacent to the riverfront district except Union'],
    specialAbility:
      'INFLUENCE: +1 (River Front; max +1 toward Hostile Takeover on eligible River Front targets)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'TAKEOVER (Hostile Takeover): +1 attacker influence when the target lot is River Front — counted only on that property’s city block\n' +
      'Screen notification: Arts Council crafted!\n' +
      'End game value: 2M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet adjacent to the riverfront district, except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'tourism-office',
    type: 'anchor',
    name: 'Tourism Office',
    subtitle: 'Anchor tenet',
    buildCost: 2,
    buildIncome: 0,
    influence: 1,
    bankValue: 2,
    endGameValue: 2,
    copies: 3,
    buildLocations: ['Any center AT adjacent to the mountain cove district except Union'],
    specialAbility:
      'INFLUENCE: +1 (Mountain Cove; max +1 toward Hostile Takeover on eligible Mountain Cove targets)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'TAKEOVER (Hostile Takeover): +1 attacker influence when the target lot is Mountain Cove — counted only on that property’s city block\n' +
      'Screen notification: Tourism office conceived!\n' +
      'End game value: 2M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet adjacent to the mountain cove district, except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'mafia',
    type: 'anchor',
    name: 'Mafia',
    subtitle: 'Anchor tenet',
    buildCost: 5,
    buildIncome: 0,
    influence: 1,
    bankValue: 4,
    endGameValue: 0,
    copies: 4,
    buildLocations: ['Any center anchor except Union'],
    specialAbility:
      'INFLUENCE: +1 (Hostile Takeover) — max +1 toward takeover when the target lot shares a city block with your built Mafia\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during your Income roll\n' +
      'EXTORTION: +$1M income from others — each opposing business property (non-anchor built lot) in the same city block as your built Mafia pays you $1M when that owner resolves Income\n' +
      'Screen notification: Mafia infiltrated!\n' +
      'End game value: 0M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet (AT) except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'media',
    type: 'anchor',
    name: 'Influencer',
    subtitle: 'Anchor tenet',
    buildCost: 2,
    buildIncome: 0,
    influence: 1,
    bankValue: 2,
    endGameValue: 0,
    copies: 4,
    buildLocations: ['Any center anchor except Union'],
    specialAbility:
      'INFLUENCE: +1 (Scandals only; max +1 combined with News Outlet — owning both still caps scandal bonus at +1)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'Screen notification: Social media influencer launched!\n' +
      'End game value: 0M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet (AT) except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'news-outlet',
    type: 'anchor',
    name: 'News Outlet',
    subtitle: 'Anchor tenet',
    buildCost: 2,
    buildIncome: 0,
    influence: 1,
    bankValue: 2,
    endGameValue: 0,
    copies: 4,
    buildLocations: ['Any center anchor except Union'],
    specialAbility:
      'INFLUENCE: +1 (Scandals only; max +1 combined with Influencer)\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during Income roll\n' +
      'Screen notification: News Outlet originated!\n' +
      'End game value: 0M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet (AT) except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'regulation-bureau',
    type: 'anchor',
    name: 'Regulation Bureau',
    subtitle: 'Anchor tenet',
    buildCost: 4,
    buildIncome: 0,
    influence: 1,
    bankValue: 4,
    endGameValue: 0,
    copies: 4,
    buildLocations: ['Any center anchor except Union'],
    specialAbility:
      'INFLUENCE: +1 for your passive modifier / −1 takeover influence for rivals’ lots on this city block — Hostile Takeover attackers gain +1 per distinct Regulation Bureau owner in the block who is not the defender\n' +
      'INCOME: +1 (block) — your other owned properties in the same city block gain +1 income during your Income roll\n' +
      'Screen notification: Regulation Bureau established!\n' +
      'End game value: 0M (only if played and built or banked)\n' +
      'Build: Any center anchor tenet (AT) except Union and already-built anchor tenets',
    category: 'anchor'
  },
  {
    id: 'anchor-wild-card',
    type: 'anchor',
    name: 'Anchor Wild Card',
    subtitle: 'Choose an anchor tenet when built',
    buildCost: 6,
    buildIncome: 0,
    influence: 1,
    bankValue: 5,
    endGameValue: 0,
    copies: 2,
    buildLocations: ['Any valid center anchor lot for the anchor you choose'],
    specialAbility:
      'Choose any standard anchor identity when you build: Church Affiliation, Farm Bureau, Port Authority, Arts Council, Tourism Office, Influencer, Mafia, News Outlet, Regulation Bureau, or Union — the lot uses that anchor’s placement rules, passive benefits, end-game value, board appearance, and build celebration.\n' +
      'Build cost is always $6M (bank $5M).\n' +
      'Screen notification matches the anchor you chose.\n' +
      'Build: Pick the anchor in the hand dialog, then place on valid lots for that anchor (center AT rules per anchor; Union uses Union lots only).',
    category: 'anchor'
  },
  {
    id: 'union',
    type: 'anchor',
    name: 'Union',
    subtitle: 'Anchor tenet',
    buildCost: 4,
    buildIncome: 0,
    influence: 1,
    bankValue: 4,
    endGameValue: 0,
    copies: 4,
    buildLocations: ['Union designated anchors only'],
    specialAbility:
      'INFLUENCE: +1 (district where this Union anchor was played)\n' +
      'INCOME (Income resolution): Same block formula as Church Affiliation — +$1M per other built property you own on this Union anchor’s city block (Union cell excluded). Each built property another founder owns on that block suffers −$1M for their Income roll only — lost income; nothing is paid to you.\n' +
      'End game value: 0M (only if played and built or banked)\n' +
      'Build: Union designated anchors only',
    category: 'anchor'
  }
]

export const actionCards: ActionCard[] = [
  {
    id: 'crossing-the-line',
    type: 'action',
    category: 'regulatory',
    name: 'Crossing the Line',
    description: 'Open up all areas of the city',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 4,
    copies: 12,
    diceRequired: false,
    actions: 'Play this card and open up all areas of the city to place the property type in the district of your choice. Property can be built based on the build cost.'
  },
  {
    id: 'rezoning',
    type: 'action',
    category: 'regulatory',
    name: 'Rezoning',
    description: 'Attempt rezoning, then build a chosen property from your hand at its build cost',
    buildCost: 0,
    buildIncome: 'Dynamic',
    bankValue: 5,
    copies: 8,
    diceRequired: true,
    diceRollRule: 'Roll 5–6 after civic influence (board-wide civic): success',
    placementRule: 'Choose a property card, then a vacant lot; roll to approve build',
    actions:
      'Pick a property card in your hand (not an anchor), then a vacant city lot. Roll the die: total 5–6 succeeds — build that property there for its build cost (income and end values follow the card). With max +1 influence from owning any built civic property anywhere on the board, natural 4–6 succeeds. 1–3 fails (or 1–3 without civic bonus): Rezoning is discarded and you cannot complete a build on that lot this attempt.',
  },
  {
    id: 'double-income',
    type: 'action',
    category: 'financial',
    name: 'Double Income',
    description: 'Double the payout from Income when played together — bank only if played alone',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 5,
    copies: 8,
    diceRequired: false,
    actions:
      'Play together with Income in the same play (before the die roll); it doubles the final Income payout after the roll. Playing Double Income alone does not run Income — you may bank it for its printed cash value only or cancel.',
  },
  {
    id: 'hostile-takeover',
    type: 'action',
    category: 'legal',
    name: 'Hostile Takeover',
    description: 'Take over another player\'s property',
    buildCost: 'Dynamic',
    buildIncome: 'Dynamic',
    bankValue: 4,
    copies: 8,
    diceRequired: true,
    diceRollRule: 'Roll 5-6: Success (defender can counter with 6)',
    placementRule:
      'Property in your city block or orthogonally adjacent to your built lot (including across one street; streets are dead zones)',
    actions:
      'Pay $1M to the property owner and roll the die. Anchor tenets modify Hostile Takeover only using the target property’s city block (district anchors, Mafia, Regulation Bureau, etc.; combine per printed rules). Natural roll plus eligible bonuses: total 5–6 succeeds — owner rolls once and only a 6 blocks; otherwise pay 120% of property value and take ownership.',
  },
  {
    id: 'scandal',
    type: 'action',
    category: 'social',
    name: 'Scandal',
    description: 'Discontinue an anchor tenant\'s influence',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 5,
    copies: 4,
    diceRequired: true,
    diceRollRule: 'Total 6+ on scandal roll (max +1 from Influencer and/or News Outlet — does not stack)',
    placementRule: 'Any built anchor property',
    actions:
      'Pick which built anchor tenet to target and roll the die. Total 6+: that anchor’s influence is discontinued (passive bonuses no longer apply). Owning built Influencer and/or News Outlet with active influence grants at most +1 to your scandal roll (both anchors still cap at +1 total). The anchor owner rolls once — a 6 negates your success.',
  },
  {
    id: 'build-with-tax-dollars',
    type: 'action',
    category: 'financial',
    name: 'Build with Tax Dollars',
    description: 'Build a property at half cost',
    buildCost: '1/2 cost',
    buildIncome: 0,
    bankValue: 5,
    copies: 4,
    diceRequired: false,
    placementRule: 'Any property you would like to build',
    actions: 'Build your property that you have in your hand with 1/2 cost.'
  },
  {
    id: 'taxation',
    type: 'action',
    category: 'regulatory',
    name: 'Taxation',
    description: 'City income assessment on all other founders',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 5,
    copies: 4,
    diceRequired: false,
    actions:
      'Assessment of tax towards improvement of city properties. When played, every other founder is assessed on their next Income resolution: their collection is reduced by 50% of their property income total for that roll (shelters and ordinary defenses do not apply). The player who played Taxation has prepared appropriate shelters and is not assessed.',
  },
  {
    id: 'police-raid-on-mafia',
    type: 'action',
    category: 'legal',
    name: 'Police Raid on Mafia',
    description: 'Counter mafia effect',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 5,
    copies: 2,
    diceRequired: true,
    diceRollRule: 'Roll 5+ succeeds (4+ with raid influence); counter threshold shifts when attacker has raid influence',
    actions:
      'Counter Mafia extortion by rolling the die. Natural roll plus max +1 raid influence if you own built Police, City Hall, and/or Courthouse anywhere on the board — total 5+ succeeds (otherwise fail). On success, the Mafia owner rolls once to counter: 6 negates if you had no raid influence; 5–6 negates if you had raid influence (+1).',
  },
  {
    id: 'investment',
    type: 'action',
    category: 'financial',
    name: 'Investment',
    description: 'Invest $4M in another founder\'s property; $1M income per owner Income resolution (25% of investment).',
    buildCost: 4,
    buildIncome: 1,
    bankValue: 4,
    endGameValue: 4,
    copies: 12,
    diceRequired: false,
    placementRule:
      'Property in your city block or orthogonally adjacent to your built lot (including across one street; streets are dead zones)',
    actions:
      'Pay $4 million to the property owner with whom you would like to invest. If invested in property, you will receive income of 25% of your investment ($1M) from the owner\'s income as the owner of the property receives income, appropriate to the investment made in the property. Does not apply to Park, Museum, Civic Center, City Hall, Courthouse, or Police. When the owner resolves Income, investor shares are paid from their collected proceeds (pro-rated if proceeds cannot cover every share).',
  },
  {
    id: 'double-investment',
    type: 'action',
    category: 'financial',
    name: 'Double Investment',
    description: 'Invest $8M in another founder\'s property; $2M income per owner Income resolution (25% of investment).',
    buildCost: 8,
    buildIncome: 2,
    bankValue: 4,
    endGameValue: 8,
    copies: 8,
    diceRequired: false,
    actions:
      'Pay $8 million to the property owner with whom you would like to invest. If invested in property, you will receive income of 25% of your investment ($2M) from the owner\'s income as the owner of the property receives income, appropriate to the investment made in the property. Does not apply to Park, Museum, Civic Center, City Hall, Courthouse, or Police. When the owner resolves Income, investor shares are paid from their collected proceeds (pro-rated if proceeds cannot cover every share).',
  },
  {
    id: 'remove-investors',
    type: 'action',
    category: 'legal',
    name: 'Remove Investors',
    description: 'Remove investors from your property',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 4,
    copies: 4,
    diceRequired: true,
    diceRollRule: 'Roll 5-6: Success',
    placementRule: 'Only against investors within your own single property',
    actions:
      'Play this card, then click one of your own built properties that still has investment stripes (there may be multiple investors on that lot). Roll the die: total 5 or higher after anchor and civic influence only in that property’s city block removes all investors from that lot. There is no counter-roll from investors. If you succeed, you pay each investor 50% of what they invested ($M), each rounded down to a whole million, then investment stripes are cleared. On a failed roll, investors stay and this card is discarded.'
  },
  {
    id: 'city-council-freeze',
    type: 'action',
    category: 'regulatory',
    name: 'City Council Freeze',
    description: 'Withhold building for one round',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 2,
    copies: 4,
    diceRequired: true,
    diceRollRule: 'Up to 3 rolls: 5–6 after influence succeeds; $5M per extra roll; defender rolls once (6 negates)',
    actions: 'Choose another player. Roll up to three times: total 5–6 after civic influence succeeds. The first roll is free; each extra roll costs $5M. +1 influence (max +1) if you own built City Hall and/or Courthouse anywhere on the board (one bonus total). If all three rolls miss, the card fails. If you succeed, the target rolls once — a 6 negates the freeze. Otherwise they cannot build properties until they finish their next turn.'
  },
  {
    id: 'draw-2-action-cards',
    type: 'action',
    category: 'social',
    name: 'Draw 2 Action Cards',
    description: 'Draw 2 more action cards',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 2,
    copies: 12,
    diceRequired: false,
    actions: 'Draw 2 more action cards.'
  },
  {
    id: 'discard-property-cards',
    type: 'action',
    category: 'social',
    name: 'Discard Property Cards',
    description: 'Discard and replace property cards',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 3,
    copies: 4,
    diceRequired: false,
    actions: 'Discard property cards of your choosing and replace them with the number of cards that you have discarded.'
  },
  {
    id: 'income',
    type: 'action',
    category: 'financial',
    name: 'Income',
    description: 'Roll for income from your properties',
    buildCost: 0,
    buildIncome: 0,
    bankValue: 4,
    copies: 40,
    diceRequired: true,
    diceRollRule: INCOME_CARD_DICE_ROLL_RULE,
    actions: INCOME_CARD_ACTIONS_BODY
  }
]
