/**
 * Even-round motivational flashes: cycled in order (one per even table round) through all lines, then repeat.
 */
export const MOTIVATIONAL_BANNER_PHRASES: readonly string[] = [
  'Build fast, think wisely—neighbors are watching.',
  'Speed wins games, but wisdom wins communities.',
  'Tiny steps, steady progress.',
  'Dream big, plan smart, build with heart.',
  'Quick builds, clear goals, lasting block.',
  'Smart choices today, a stronger block tomorrow.',
  'Neighbors notice reckless brilliance.',
  'Purpose over impulse—build for good.',
  'Every brick helps shape the future.',
  "Collaborate, don't cramp—this City thrives together.",
  'Hustle with heart; skip the ego.',
  'They said hurry; you said think twice.',
  'Great layouts respect space and people.',
  'Turn chaos into cohesion with a plan.',
  'A strong City is a shared City.',
  'The most elegant builds are mindful builds.',
  'Let purpose guide every blueprint.',
  'Neighbors make the City shine.',
  'Think long-term—the banner outlasts your turn.',
  'Quick decisions, kind outcomes.',
  'Clarity over clutter—build what matters.',
  'A thriving block starts with thoughtful placement.',
  'Build for the future you want to live in.',
  'Final reminder: neighbors first, profits second.',
  'Shortcuts build drama, not bridges.',
  'Clear plan, quiet power.',
  'A plan keeps chaos away.',
  'Quick win, lasting stain.',
  'Think twice, build once.',
  'Plan outlasts ego.',
  'Patience pays, pride complains.',
  'Neighbors deserve better than chaos.',
  'Efficiency with empathy persists.',
  'Thoughtful layouts win crowds.',
]
